// 把 src/icons.json 列出的 Font Awesome 图标编译成一张 SVG sprite。
//
// 为什么是 sprite 而不是图标字体：字体要 248 KB 且在首屏关键路径上，还有
// 加载闪烁；sprite 只装用到的图标，随 currentColor 变色，一次请求可长缓存。
//
// FA 包是 devDependency，只在构建时读。产出 assets/dist/icons.svg 提交进
// 仓库 —— 消费者不装 Node。

import { readFile, writeFile } from "node:fs/promises";

// 清单放 data/ 而不是 src/：Hugo 从 data/ 读 site.Data，模板据此校验图标名。
// 构建脚本与模板读同一个文件，不维护两份名单。
const MANIFEST = "data/icons.json";
const FA = "node_modules/@fortawesome/fontawesome-free/svgs";
const OUT = "assets/dist/icons.svg";

// CC BY 4.0 要求署名。它必须留在产出文件里，不能只写在仓库文档中。
const NOTICE =
  "Font Awesome Free icons -- CC BY 4.0 -- https://fontawesome.com/license/free";

const manifest = JSON.parse(await readFile(MANIFEST, "utf8"));
const entries = Object.entries(manifest).filter(([id]) => !id.startsWith("$"));

if (entries.length === 0) {
  console.error(`${MANIFEST} lists no icons`);
  process.exit(1);
}

const symbols = [];
const missing = [];

for (const [id, source] of entries) {
  const [style, name] = String(source).split("/");
  if (!style || !name) {
    missing.push(`${id}: ${source} is not "style/name"`);
    continue;
  }

  let svg;
  try {
    svg = await readFile(`${FA}/${style}/${name}.svg`, "utf8");
  } catch {
    missing.push(`${id}: ${style}/${name}.svg not found`);
    continue;
  }

  // 只取 viewBox 与路径内容。FA 的 svg 带 xmlns 和注释，进了 sprite 是噪音。
  const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1];
  const body = svg.match(/<svg[^>]*>([\s\S]*?)<\/svg>/)?.[1];
  if (!viewBox || !body) {
    missing.push(`${id}: could not parse ${style}/${name}.svg`);
    continue;
  }

  symbols.push(
    `<symbol id="${id}" viewBox="${viewBox}">${body.replace(/<!--[\s\S]*?-->/g, "").trim()}</symbol>`,
  );
}

// 缺图标是构建错误，不是警告。静默产出一张缺项的 sprite 会让页面上出现
// 空白方块，而错误发生在几步之前。
if (missing.length > 0) {
  console.error(`icons: ${missing.length} unresolved\n  ${missing.join("\n  ")}`);
  process.exit(1);
}

const sprite = `<svg xmlns="http://www.w3.org/2000/svg" style="display:none">
<!-- ${NOTICE} -->
<!-- Generated by scripts/build-icons.js from src/icons.json -- do not edit. -->
${symbols.join("\n")}
</svg>
`;

await writeFile(OUT, sprite, "utf8");
console.log(`icons: ${symbols.length} symbols -> ${OUT} (${(sprite.length / 1024).toFixed(1)} KB)`);
