// 生成 Chroma 类名样式表，整块包进门控选择器。
// Chroma 只输出扁平规则，而 @import 不能嵌在选择器里 —— 所以包裹在这里
// 做。用原生 CSS 嵌套，Lightning CSS 编译时展开，不靠正则改选择器。
import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";

const OUT = "src/css/vendor";

const variants = [
  { style: "github", gate: ':root:not([data-td-theme="dark"])', file: "chroma-light.css" },
  { style: "github-dark", gate: '[data-td-theme="dark"]', file: "chroma-dark.css" },
];

mkdirSync(OUT, { recursive: true });

for (const { style, gate, file } of variants) {
  const raw = execFileSync("hugo", ["gen", "chromastyles", `--style=${style}`], {
    encoding: "utf8",
  });
  const body = raw
    .split("\n")
    .map((l) => (l.trim() ? `  ${l}` : l))
    .join("\n");
  const out = `/* Generated by scripts/gen-chroma.js from chroma "${style}". Do not edit. */
${gate} {
${body}
}
`;
  writeFileSync(`${OUT}/${file}`, out, "utf8");
  console.log(`${OUT}/${file}`);
}
